import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { Activity, ArrowLeft, UserPlus, UserRoundPen, UserX } from "lucide-react";
import { BusinessLayout } from "@/components/business/BusinessLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/lib/supabaseClient";
import { usePermissions } from "@/hooks/use-permissions";

const labels: Record<string,string>={created:"Cadastro",updated:"Alteração",deleted:"Remoção"};
const icons: Record<string,any>={created:UserPlus,updated:UserRoundPen,deleted:UserX};
export default function HrHistory(){
 const {slug}=useParams<{slug:string}>(); const {toast}=useToast(); const [company,setCompany]=useState<any>(null); const [user,setUser]=useState<any>(null); const [employees,setEmployees]=useState<any[]>([]); const [events,setEvents]=useState<any[]>([]); const [employeeId,setEmployeeId]=useState("all"); const [loading,setLoading]=useState(true);
 useEffect(()=>{load()},[slug]);
 async function load(){setLoading(true);try{const {data:a}=await supabase.auth.getUser();if(!a.user)return;setUser(a.user);const {data:c,error:ce}=await supabase.from("companies").select("id,name,slug,owner_email").eq("slug",slug).single();if(ce)throw ce;setCompany(c);const [{data:e,error:ee},{data:h,error:he}]=await Promise.all([supabase.from("employees").select("id,name").eq("company_id",c.id).order("name"),supabase.from("employee_history").select("id,employee_id,event_type,title,description,old_data,new_data,created_at").eq("company_id",c.id).order("created_at",{ascending:false})]);if(ee)throw ee;if(he)throw he;setEmployees(e||[]);setEvents(h||[])}catch(e:any){toast({title:"Erro ao carregar histórico",description:e.message,variant:"destructive"})}finally{setLoading(false)}}
 const {hasPermission,loading:pl,userRole}=usePermissions(company?.id,user); const isAdmin=userRole==="owner"||userRole==="admin"; const canView=isAdmin||hasPermission("hr.manage_employees")||hasPermission("hr.view"); const names=useMemo(()=>Object.fromEntries(employees.map(e=>[e.id,e.name])),[employees]); const filtered=employeeId==="all"?events:events.filter(e=>e.employee_id===employeeId);
 if(loading||pl)return <BusinessLayout companySlug={slug||""} companyName="Carregando..." companyId="" userRole="loading"><div className="p-10 text-center">Carregando...</div></BusinessLayout>;
 if(!canView)return <BusinessLayout companySlug={slug||""} companyName="Histórico" companyId={company?.id||""} userRole={isAdmin?"owner":userRole}><div className="p-10 text-center">Acesso negado.</div></BusinessLayout>;
 return <BusinessLayout companySlug={company.slug} companyName={company.name} companyId={company.id} userRole={isAdmin?"owner":userRole} currentUser={user}><div className="p-4 sm:p-6 sm:px-10 space-y-6"><div><Button variant="ghost" asChild className="px-0 mb-2"><Link to={`/${company.slug}/admin/recursos-humanos`}><ArrowLeft className="w-4 h-4 mr-2"/>Recursos Humanos</Link></Button><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 className="text-3xl font-bold">Histórico</h1><p className="text-muted-foreground">Linha do tempo das principais alterações administrativas dos colaboradores.</p></div><div className="w-full md:w-64"><Select value={employeeId} onValueChange={setEmployeeId}><SelectTrigger><SelectValue placeholder="Todos os colaboradores"/></SelectTrigger><SelectContent><SelectItem value="all">Todos os colaboradores</SelectItem>{employees.map(e=><SelectItem key={e.id} value={e.id}>{e.name}</SelectItem>)}</SelectContent></Select></div></div></div><Card><CardHeader><CardTitle>Linha do tempo</CardTitle><CardDescription>{filtered.length} registro(s)</CardDescription></CardHeader><CardContent>{filtered.length===0?<div className="py-12 text-center text-muted-foreground">Nenhum evento registrado.</div>:<div className="space-y-5">{filtered.map((event,i)=>{const Icon=icons[event.event_type]||Activity;return <div key={event.id} className="relative flex gap-4">{i<filtered.length-1&&<div className="absolute left-4 top-9 bottom-[-20px] w-px bg-border"/>}<div className="relative z-10 rounded-full bg-primary/10 p-2 text-primary h-8 w-8 shrink-0"><Icon className="w-4 h-4"/></div><div className="min-w-0 flex-1 border rounded-lg p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-semibold">{event.title}</p><p className="text-sm text-muted-foreground">{names[event.employee_id]||event.description||"Colaborador"}</p></div><Badge variant="outline">{labels[event.event_type]||event.event_type}</Badge></div><p className="text-xs text-muted-foreground mt-2">{new Date(event.created_at).toLocaleString("pt-BR")}</p>{event.event_type==="updated"&&event.old_data&&event.new_data&&<div className="mt-3 text-sm text-muted-foreground">Alteração administrativa registrada no cadastro do colaborador.</div>}</div></div>})}</div>}</CardContent></Card></div></BusinessLayout>;
}