import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { Activity, Archive, ArrowRight, CalendarDays, CheckCircle2, ClipboardList, Clock3, FileText, HeartPulse, Plus, Users } from "lucide-react";
import { BusinessLayout } from "@/components/business/BusinessLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { supabase } from "@/lib/supabaseClient";
import { usePermissions } from "@/hooks/use-permissions";

interface Company { id:string; name:string; slug:string; owner_email?:string|null }
interface Employee { id:string; name:string; role:string|null; is_active:boolean|null; created_at:string }
const hrModules=[
 {title:"Colaboradores",description:"Cadastro, edição, status, serviços e permissões dos colaboradores.",permission:"hr.manage_employees",icon:Users,path:"colaboradores",action:"Gerenciar"},
 {title:"Férias",description:"Organização, solicitações, aprovações e histórico de férias.",permission:"hr.manage_vacations",icon:CalendarDays,path:"ausencias",action:"Gerenciar"},
 {title:"Afastamentos",description:"Registro e acompanhamento de afastamentos e ocorrências.",permission:"hr.manage_absences",icon:HeartPulse,path:"ausencias",action:"Gerenciar"},
 {title:"Jornada / Ponto",description:"Jornadas, escalas, ponto, horas extras e banco de horas.",permission:"hr.manage_attendance",icon:Clock3,path:"horarios",action:"Gerenciar"},
 {title:"Documentos",description:"Documentos administrativos e histórico documental dos colaboradores.",permission:"hr.manage_documents",icon:FileText,path:"recursos-humanos/documentos",action:"Gerenciar"},
 {title:"Avaliações",description:"Avaliações de desempenho, feedbacks e histórico profissional.",permission:"hr.manage_evaluations",icon:ClipboardList,path:"recursos-humanos/avaliacoes",action:"Gerenciar"},
 {title:"Histórico",description:"Linha do tempo das principais alterações administrativas do colaborador.",permission:"hr.manage_employees",icon:Activity,path:"recursos-humanos/historico",action:"Ver histórico"},
];
function roleLabel(role:string|null){const labels:Record<string,string>={owner:"Proprietário",admin:"Administrador",manager:"Gerente",supervisor:"Supervisor",receptionist:"Recepcionista",employee:"Funcionário",rh:"RH",marketing:"Marketing",designer:"Designer"};return role?labels[role]||role:"Sem função definida"}
export default function HumanResources(){
 const {slug}=useParams<{slug:string}>();const [company,setCompany]=useState<Company|null>(null);const [employees,setEmployees]=useState<Employee[]>([]);const [currentUser,setCurrentUser]=useState<any>(null);const [userRole,setUserRole]=useState("employee");const [loading,setLoading]=useState(true);
 useEffect(()=>{loadData()},[slug]);
 const loadData=async()=>{setLoading(true);try{const [{data:companyData,error:companyError},{data:authData}]=await Promise.all([supabase.from("companies").select("id,name,slug,owner_email").eq("slug",slug).single(),supabase.auth.getUser()]);if(companyError)throw companyError;if(!companyData||!authData.user)return;setCompany(companyData);setCurrentUser(authData.user);const {data:employee}=await supabase.from("employees").select("id,role").eq("company_id",companyData.id).eq("user_id",authData.user.id).maybeSingle();const isCompanyOwner=String(companyData.owner_email??"").trim().toLowerCase()===String(authData.user.email??"").trim().toLowerCase();setUserRole(isCompanyOwner?"owner":employee?.role||"employee");const {data:employeesData,error:employeesError}=await supabase.from("employees").select("id,name,role,is_active,created_at").eq("company_id",companyData.id).order("name");if(employeesError)throw employeesError;setEmployees(employeesData||[])}catch(error){console.error("Error loading HR data:",error)}finally{setLoading(false)}};
 const {hasPermission,loading:permissionLoading,userRole:permissionRole}=usePermissions(company?.id,currentUser);const isAdministrator=userRole==="owner"||userRole==="admin"||permissionRole==="owner"||permissionRole==="admin";const canView=isAdministrator||hasPermission("hr.view");const activeEmployees=useMemo(()=>employees.filter(e=>e.is_active!==false),[employees]);const inactiveEmployees=employees.length-activeEmployees.length;const recentEmployees=useMemo(()=>[...employees].sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime()).slice(0,5),[employees]);
 if(loading||permissionLoading)return <BusinessLayout companySlug={slug||""} companyName="Carregando..." companyId="" userRole="loading"><div className="flex items-center justify-center min-h-[60vh]"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"/></div></BusinessLayout>;
 if(!company||!currentUser||!canView)return <BusinessLayout companySlug={slug||""} companyName={company?.name||"Acesso Negado"} companyId={company?.id||""} userRole={isAdministrator?"owner":userRole} currentUser={currentUser}><div className="p-6 flex items-center justify-center min-h-[60vh]"><Card className="max-w-md w-full"><CardHeader><CardTitle>Acesso Negado</CardTitle><CardDescription>Você não possui a permissão para visualizar Recursos Humanos.</CardDescription></CardHeader></Card></div></BusinessLayout>;
 const layoutRole=isAdministrator?"owner":userRole;const basePath=`/${company.slug}/admin`;const visibleModules=hrModules.filter(m=>isAdministrator||hasPermission(m.permission));
 return <BusinessLayout companySlug={company.slug} companyName={company.name} companyId={company.id} userRole={layoutRole} currentUser={currentUser}><div className="p-4 sm:p-6 sm:px-10 w-full space-y-6"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h1 className="text-3xl font-bold text-gradient">Recursos Humanos</h1><p className="text-muted-foreground mt-1">Gestão administrativa e acompanhamento da equipe da empresa.</p></div>{(isAdministrator||hasPermission("hr.manage_employees"))&&<Button asChild variant="neon"><Link to={`${basePath}/colaboradores`}><Plus className="w-4 h-4 mr-2"/>Novo colaborador</Link></Button>}</div>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Link to={`${basePath}/colaboradores`} className="block"><Card className="h-full transition-colors hover:border-primary/50"><CardContent className="p-5 flex items-center justify-between"><div><p className="text-sm text-muted-foreground">Colaboradores</p><p className="text-2xl font-bold mt-1">{employees.length}</p></div><Users className="w-8 h-8 text-primary"/></CardContent></Card></Link><Card><CardContent className="p-5 flex items-center justify-between"><div><p className="text-sm text-muted-foreground">Ativos</p><p className="text-2xl font-bold mt-1">{activeEmployees.length}</p></div><CheckCircle2 className="w-8 h-8 text-primary"/></CardContent></Card><Card><CardContent className="p-5 flex items-center justify-between"><div><p className="text-sm text-muted-foreground">Inativos</p><p className="text-2xl font-bold mt-1">{inactiveEmployees}</p></div><Archive className="w-8 h-8 text-muted-foreground"/></CardContent></Card><Link to={`${basePath}/ausencias`} className="block"><Card className="h-full transition-colors hover:border-primary/50"><CardContent className="p-5 flex items-center justify-between"><div><p className="text-sm text-muted-foreground">Ausências</p><p className="text-sm font-semibold mt-2">Gerenciar registros</p></div><HeartPulse className="w-8 h-8 text-primary"/></CardContent></Card></Link></div>
 <Card><CardHeader><CardTitle>Módulos de RH</CardTitle><CardDescription>Acesse diretamente cada área disponível.</CardDescription></CardHeader><CardContent><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visibleModules.map(module=>{const Icon=module.icon;return <Link key={module.title} to={`${basePath}/${module.path}`}><Card className="h-full bg-card/60 transition-colors hover:border-primary/50"><CardContent className="p-5 h-full flex flex-col"><div className="flex items-start gap-3 flex-1"><div className="rounded-lg bg-primary/10 p-2 text-primary"><Icon className="w-5 h-5"/></div><div className="min-w-0 flex-1"><h3 className="font-semibold">{module.title}</h3><p className="text-sm text-muted-foreground mt-1">{module.description}</p></div></div><div className="mt-4 flex justify-end"><span className="text-sm font-medium text-primary flex items-center gap-1">{module.action}<ArrowRight className="w-4 h-4"/></span></div></CardContent></Card></Link>})}</div></CardContent></Card>
 <Card><CardHeader><CardTitle>Equipe</CardTitle><CardDescription>Visão rápida dos colaboradores cadastrados na empresa.</CardDescription></CardHeader><CardContent>{recentEmployees.length===0?<div className="py-10 text-center text-muted-foreground">Nenhum colaborador cadastrado.</div>:<div className="space-y-3">{recentEmployees.map((employee,index)=><div key={employee.id}><Link to={`${basePath}/colaboradores`} className="flex items-center justify-between gap-4 py-2 rounded-md hover:bg-muted/40 px-2 -mx-2 transition-colors"><div className="min-w-0"><p className="font-medium truncate">{employee.name}</p><p className="text-sm text-muted-foreground">{roleLabel(employee.role)}</p></div><Badge variant={employee.is_active===false?"secondary":"outline"}>{employee.is_active===false?"Inativo":"Ativo"}</Badge></Link>{index<recentEmployees.length-1&&<Separator/>}</div>)}</div>}</CardContent></Card>
 <div className="flex flex-wrap gap-3">{(isAdministrator||hasPermission("hr.manage_documents"))&&<Button asChild variant="outline"><Link to={`${basePath}/recursos-humanos/documentos`}><FileText className="w-4 h-4 mr-2"/>Documentos</Link></Button>}{(isAdministrator||hasPermission("hr.manage_evaluations"))&&<Button asChild variant="outline"><Link to={`${basePath}/recursos-humanos/avaliacoes`}><ClipboardList className="w-4 h-4 mr-2"/>Avaliações</Link></Button>}{(isAdministrator||hasPermission("hr.manage_employees"))&&<Button asChild variant="outline"><Link to={`${basePath}/recursos-humanos/historico`}><Activity className="w-4 h-4 mr-2"/>Histórico</Link></Button>}</div>
 </div></BusinessLayout>;
}